Repository wecode-bootcamp-korea/24-2nd-METABOX-backend, pull requests merged in 2021-09, with the labels that each got.

#1 [METABOX]models.py 작성
  bookings/__init__.py
  bookings/admin.py
  bookings/apps.py
  bookings/migrations/__init__.py
  bookings/models.py
  bookings/tests.py
  bookings/views.py
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/views.py
  movieposts/__init__.py
  movieposts/admin.py
  movieposts/apps.py
  movieposts/migrations/__init__.py
  movieposts/models.py
  movieposts/tests.py
  movieposts/views.py
  movies/__init__.py
  movies/admin.py
  movies/apps.py
  movies/migrations/__init__.py
  movies/models.py
  movies/tests.py
  movies/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: Status: 리뷰 요청

#2 [METABOX] Modified: initial setting & models.py
  bookings/models.py
  config/settings.py
  movieposts/models.py
  movies/models.py
Labels: Status: 리뷰 요청

#4 [METABOX] Modified : bookings/models.py 수정
  bookings/models.py
Labels: Status: 리뷰 요청

#3 [송치헌] ADD : bookings/views.py 작성&로그인 데코레이터 작성 & 모델 일부 수정
  bookings/migrations/0001_initial.py
  bookings/migrations/0002_auto_20210918_1413.py
  bookings/migrations/0003_auto_20210919_1639.py
  bookings/models.py
  bookings/tests.py
  bookings/urls.py
  bookings/views.py
  config/settings.py
  config/urls.py
  core/utils.py
  decorators.py
  movieposts/migrations/0001_initial.py
  movieposts/models.py
  movies/migrations/0001_initial.py
  movies/models.py
  users/migrations/0001_initial.py
  users/migrations/0002_alter_user_birth_day.py
  users/models.py
Labels: Status: 도움 요청, Status: 리뷰 요청

#5 [윤현묵] movie view 작성
  bookings/migrations/0001_initial.py
  bookings/migrations/0002_auto_20210918_1413.py
  bookings/models.py
  config/settings.py
  config/urls.py
  core/migrations/__init__.py
  movieposts/migrations/0001_initial.py
  movies/migrations/0001_initial.py
  movies/tests.py
  movies/urls.py
  movies/views.py
  users/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#8 [METABOX] Modified : booking view changed - 송치헌
  bookings/tests.py
  bookings/urls.py
  bookings/views.py
Labels: Status: 리뷰 요청

#7 [주종민] ADD : KAKAO API
  bookings/migrations/0001_initial.py
  config/settings.py
  config/urls.py
  movieposts/migrations/0001_initial.py
  movies/migrations/0001_initial.py
  movies/models.py
  users/migrations/0001_initial.py
  users/migrations/0002_alter_user_birth_day.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#10 [송치헌] Modified : booking view changed6
  bookings/migrations/0001_initial.py
  bookings/migrations/0002_auto_20210918_1413.py
  bookings/migrations/0003_auto_20210919_1639.py
  bookings/views.py
  movieposts/migrations/0001_initial.py
  movieposts/tests.py
  movieposts/views.py
Labels: Status: Conflict 해결 요청

#9 [윤현묵] 영화 전체 리스트뷰 작성
  movies/tests.py
  movies/urls.py
  movies/views.py
Labels: Status: 리뷰 요청

#11 [송치헌]modified : last modify
  bookings/views.py
  users/views.py
Labels: Status: 리뷰 요청

#12 [주종민] ADD : KAKAO API and UnitTest
  users/tests.py
  users/views.py
Labels: Status: 리뷰 요청
